### PR TITLE
Create Rectangular convex suction

### PR DESCRIPTION
**Pull request by Connor-Devitt**
New strategy based on 1/6/15 discussion

### CODE REVIEW

**Comment by msbense** [comment]
Thanks! Kinda changed my mind about using Github, could you fork Design at gist.github.com/msbense and repost this there? Gist might be better as its for small files/ideas

**Comment by Connor-Devitt** [comment]
We are not using git for the design anymore??

**Comment by msbense** [comment]
I dunno, it didn't seem like people were open to it. Too complicated, etc. What do you think?

**Comment by Connor-Devitt** [comment]
I think it is a great idea. I do not think learning it will be difficult. Tomorrow let's just do a demo and everyone will understand.

I am not sure how to post to Gist...

**Comment by Connor-Devitt** [comment]
It forces people to think out their ideas and add to other people's ideas (like you said)
. I think we should use it

**Pull request merged**
